language: node_js
node_js:
- '8'
sudo: required
services:
- docker
branches:
  only:
  - master
jobs:
  include:
  - stage: Build docker
    script: "./travis_scripts/docker-build.sh"
    if: branch = master
env:
  global:
  - secure: vMQHojlDyoBeoinyDCcGvyXlOejAWcmhdDaOTPFkCY7iG+XMGxrUKzN6QKHFa1tCPspR3lyRGwrlfij0e8FYDfFR9oBQOxe4ts4XzW6fwnmkwtlJaq2cMrvwxX79jt49p7quDuM6ckZmbbcpVY4dV9dSHR2Nh9v7NsSBw2Tpo+hEeZ8ilLfbjyzS/ztxKAL2o9ZnnQXnlf/XQre/6w4VOn7dwfkC1sCkFhbUnDHaewrVkHWl0gGWxNWc/+RvmDoI20wAzYT/7N1SG0YQM/aZoiC3SYnWrLf5isw9mWodaEUwT9O1snOAyjl16UKDShzyer/186dVAWEuxULPRs6HbLCAF9DV85Njd7y3DMTO+GiyIoQUctACGKMBLwT82dpClhGiyOoBBpwq4L7PRbMq2Jxb7pA3tOFwwSqdaMVulvJDPauV/m8kq9uxZ+4JADlQYjUmbiTFSr2kUImJHAzvg167G3hFCrm98IkRWYLoE+B5ouIY6fdV0A6QwKL152Dqrie6r8R8BsITt309wSXrIYgYIs6x2pnAsnQhElXqZqg/Zp7Tp935Aw6F1UQKsNw8IIP2HEygnA59SnFn4VRzJxOillvPQ636+6bgoOfvTQZducVuJlkga4tXJs/uBzamJ4Fc7HDD6uZIoLnANmedk/1TqDtWRZuCgPhy7dESi4I=
  - secure: 2D2v0MnwiY7PcOo5b6h8UvhqAS3pBI9jfcfKOB+EKOHkCPHDdKKLE1GNF/Z3CwjkuHTyCPn9qFqXm2lfxYx4O38n99HTsfOboIK4YH0UsbMKX9SMp8zh9nKTGbQ6uBt7hlwXjMGb2nLgfTeQkY//vdWrYU3KvNDmZsdhsKsjbGPDekv5Brt89E9zHFhn1dW+jKBOUnoPNgCaZEDI2x32aajO0Enwb6YEpdFxpeP/JzdIRWZB4pNLTjynV7TW6IMe1vVDvjJEpTAOFcDCzl+hEvP8LqFk6cZWMd+FtNoLeXVTY45w26PqZumGx5xASHWCb4ZntQMqnN4SOOXXQBNJfb+j/hejaZ1Bqd+F0IHk6SbOVNsERqcGT6fm/fetAFOGZjTCHrdRguOy0kjLTSYRBxGYMulYEr7HTipB1bcPyH9FbsXrjqXaN6+fKqsvMHV2CVcFDEHOlPMEf3/XGuzN+vw35V55XMr+51gT4aJjPTzJfxqspt/Yk7yIdmyjne8IWGwnQ80G/CmvAaO145X2xGxAByZK60N641VgZv5Msejm0A83zhyZvIQow4FTaMalFx1nS0j60E68vd4ge6Orsh35AQ+7OGnhyeUM1v6APsFRoHNksn4BO4ty4azVk/oTpXg0fmw+qv7fcgWNKB61r0+wuSYVdDAyWLPRDAUnfg4=
